// -- user code here --

/* --- start generated code --- */

// Generated by Phaser Editor v1.4.1 (Phaser v2.6.2)

/**
 * About.
 */
function About() {

	Phaser.State.call(this);

}

/** @type Phaser.State */
var About_proto = Object.create(Phaser.State.prototype);
About.prototype = About_proto;
About.prototype.constructor = About;

About.prototype.init = function() {

};

About.prototype.preload = function() {

	this.load.pack('Story', 'assets/assets-pack.json');

};

About.prototype.create = function() {
	var _s1 = this.add.sprite(160, 90, '1');
	_s1.name = '1';

};

/* --- end generated code --- */
// -- user code here --
